ALTER TABLE photos ADD COLUMN original_size_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE photos ADD COLUMN optimized_size_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE photos ADD COLUMN storage_size_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE photos ADD COLUMN storage_saved_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE photos ADD COLUMN variant_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE photos ADD COLUMN phash TEXT;
CREATE INDEX IF NOT EXISTS idx_photos_phash ON photos(phash);
