USE filmstocks;

-- Admin user  password: Admin1234!
INSERT INTO users (username, email, password_hash, role) VALUES
('admin', 'admin@filmstocks.dev', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewYpfQN6fJ9Y9K3m', 'admin');

-- Film stocks: B&W
INSERT INTO film_stocks (name, brand, type, iso, description, characteristics) VALUES
('Tri-X 400',        'Kodak',  'bw', 400,
 'The legendary workhorse of photojournalism. Tri-X has been capturing decisive moments since 1954.',
 'High contrast, pronounced grain, wide exposure latitude, beautiful tonal range'),
('T-Max 100',        'Kodak',  'bw', 100,
 'Kodak''s sharpest black-and-white film. T-Max 100 is built for maximum resolution and smoothness.',
 'Extremely fine grain, T-grain technology, exceptional sharpness, clean midtones'),
('T-Max 400',        'Kodak',  'bw', 400,
 'The modern high-speed answer to Tri-X. T-Max 400 pushes cleanly to 1600 and beyond.',
 'Fine grain for ISO 400, excellent push performance, tabular grain, wide tonal range'),
('HP5 Plus',         'Ilford', 'bw', 400,
 'The most versatile black-and-white film ever made. Push it, pull it — HP5 handles anything.',
 'Fine grain for the speed, excellent shadow detail, great pushing to 3200'),
('Delta 100',        'Ilford', 'bw', 100,
 'Ilford''s precision Delta technology at its finest. Delta 100 is for photographers who demand perfection.',
 'Ultra-fine Delta-crystal grain, high acutance, long tonal scale, superb shadow and highlight detail'),
('Delta 3200',       'Ilford', 'bw', 3200,
 'When the lights go out, Delta 3200 steps in. The ultimate low-light film.',
 'Very coarse expressive grain, incredible low-light performance, moody atmosphere'),
('FP4 Plus',         'Ilford', 'bw', 125,
 'The precision tool. FP4 rewards careful metering with silky smooth tones.',
 'Ultra-fine grain, exceptional sharpness, long tonal scale, studio-grade quality'),
('SFX 200',          'Ilford', 'bw', 200,
 'Infrared-sensitive panchromatic film with an extended red response. SFX creates otherworldly results.',
 'Extended red sensitivity, with a 720nm filter near-infrared effect, dramatic skies, glowing foliage'),
('Ortho Plus',       'Ilford', 'bw', 80,
 'Orthochromatic film that sees the world differently — no red sensitivity, ultra-smooth gradation.',
 'Orthochromatic sensitivity, very fine grain, smooth skin rendering, exceptional sharpness'),
('Fomapan 400',      'Foma',   'bw', 400,
 'Czech craftsmanship at a budget price. Fomapan 400 rewards photographers willing to learn its quirks.',
 'Pronounced classic grain, budget-friendly, high contrast, expressive character'),
('APX 100',          'Agfa',   'bw', 100,
 'A classic reborn. Agfa APX 100 brings European fine-art tradition to modern photography.',
 'Very fine grain, excellent midtone separation, slightly warm tone, smooth highlights'),
('Rollei Infrared 400','Rollei','bw', 400,
 'True infrared-sensitive film for ethereal, dreamlike imagery. Shoot it in daylight with an IR filter.',
 'Infrared sensitive up to 820nm, dramatic IR effect, high contrast, halation around highlights');

-- Film stocks: Color Negative
INSERT INTO film_stocks (name, brand, type, iso, description, characteristics) VALUES
('Portra 160',       'Kodak',   'color_negative', 160,
 'The slow sibling of the Portra family. Portra 160 is Kodak''s finest-grained color negative film.',
 'Extremely fine grain, natural skin tones, lower contrast than 400, exceptional highlight rolloff'),
('Portra 400',       'Kodak',   'color_negative', 400,
 'The gold standard of portrait film. Portra renders skin tones with unmatched warmth.',
 'Natural skin tones, warm palette, fine grain, forgiving overexposure latitude'),
('Portra 800',       'Kodak',   'color_negative', 800,
 'The fastest professional Kodak color film. Portra 800 brings the Portra look to low-light situations.',
 'Visible grain with Portra character, excellent push to 1600, warm skin tones, indoor-ready'),
('Gold 200',         'Kodak',   'color_negative', 200,
 'Nostalgic, warm, unmistakably Kodak. Gold 200 is sunshine in a canister.',
 'Warm golden tones, visible grain adds character, classic look, budget friendly'),
('ColorPlus 200',    'Kodak',   'color_negative', 200,
 'Kodak''s entry-level color film with a distinctly retro palette. The choice for casual sunny-day shooting.',
 'Warm palette, obvious grain, budget price point, cheerful colors, great in bright sunlight'),
('Ultramax 400',     'Kodak',   'color_negative', 400,
 'Modern Kodak color for everyday shooting. More neutral than Gold, more accessible than Portra.',
 'Neutral palette, versatile in mixed light, consumer-friendly contrast'),
('Ektar 100',        'Kodak',   'color_negative', 100,
 'The finest-grained color negative film ever made. Ektar is for when detail matters most.',
 'Extremely fine grain, high saturation, punchy colors, best in bright light'),
('Superia 200',      'Fujifilm','color_negative', 200,
 'Fujifilm''s classic budget color film. Superia 200 has a distinctive cool-green palette all its own.',
 'Cool-green palette, fine grain, vivid colors, reliable in daylight, economical'),
('Superia 400',      'Fujifilm','color_negative', 400,
 'Fujifilm''s everyday workhorse. Superia delivers punchy colors and reliable results.',
 'Cool-leaning palette, fine grain, vivid greens, excellent daylight performance'),
('Superia X-TRA 400','Fujifilm','color_negative', 400,
 'The more contrasty, vivid take on Superia. X-TRA pops in mixed and indoor light.',
 'Higher saturation than standard Superia, punchy greens and blues, good indoor performance'),
('Lomo 400',         'Lomography','color_negative', 400,
 'Lomography''s general-purpose color film. Expect warm tones, slight vignetting, and analog personality.',
 'Warm tones, slight grain, some vignetting wide open, fun for everyday shooting'),
('Lomo 800',         'Lomography','color_negative', 800,
 'Push the limits of color negative. Lomo 800 thrives in low light with a punchy, saturated look.',
 'High ISO color negative, vivid saturation, expressive grain, great for parties and concerts'),
('Cinestill 800T',   'Cinestill','color_negative', 800,
 'Motion picture film adapted for still cameras. Cinestill 800T is famous for its electric halation glow.',
 'Tungsten-balanced, dramatic red halation around highlights, cinematic look, excellent low-light'),
('Cinestill 400D',   'Cinestill','color_negative', 400,
 'The daylight companion to 800T. Cinestill 400D brings the movie-still look to bright conditions.',
 'Daylight-balanced, subtle halation, fine grain, warm cinematic palette, versatile'),
('Pro 400H',         'Fujifilm','color_negative', 400,
 'Discontinued but legendary. Pro 400H''s pastel skin tones and highlight rolloff are still unmatched.',
 'Pastel skin tones, cool palette, extremely forgiving in highlights, beloved by wedding photographers');

-- Film stocks: Reversal / Slide
INSERT INTO film_stocks (name, brand, type, iso, description, characteristics) VALUES
('Velvia 50',        'Fujifilm','reversal', 50,
 'The most vivid film ever made. Velvia 50 has defined landscape photography for decades.',
 'Extreme saturation, ultra-fine grain, high contrast, iconic emerald greens'),
('Velvia 100',       'Fujifilm','reversal', 100,
 'More versatile than Velvia 50 with the same legendary color intensity. Velvia at usable speed.',
 'Very high saturation, fine grain, slightly lower contrast than Velvia 50, better in mixed light'),
('Provia 100F',      'Fujifilm','reversal', 100,
 'The balanced slide film. Provia delivers natural colors without Velvia''s intensity.',
 'Neutral color balance, very fine grain, moderate contrast, versatile subject range'),
('Astia 100F',       'Fujifilm','reversal', 100,
 'Discontinued but iconic. Astia was Fujifilm''s portrait slide film — soft, refined, unforgettable.',
 'Soft color rendering, pastel-leaning, exceptional skin tones, fine grain, lower contrast'),
('Ektachrome E100',  'Kodak',  'reversal', 100,
 'Brought back from the dead in 2018. Ektachrome is the classic American slide film.',
 'Clean neutral palette, fine grain, slightly cooler than Fuji films, archival quality'),
('Kodachrome 64',    'Kodak',  'reversal', 64,
 'The most famous film ever made. Kodachrome was discontinued in 2009 but lives on in memory and legend.',
 'Unmistakable warm palette, extremely fine dye-transfer grain, legendary archival stability, iconic look'),
('E100VS',           'Kodak',  'reversal', 100,
 'Kodak''s high-saturation slide film from the Ektachrome era. Vivid, punchy, and beautifully sharp.',
 'High saturation, fine grain, punchy blues and reds, excellent sharpness');

UPDATE film_stocks SET cover_image_url = '/film-thumbnails/tri-x-400.jpg' WHERE name = 'Tri-X 400';
UPDATE film_stocks SET cover_image_url = '/film-thumbnails/hp5-plus.jpg' WHERE name = 'HP5 Plus';
UPDATE film_stocks SET cover_image_url = '/film-thumbnails/portra-400.jpeg' WHERE name = 'Portra 400';
UPDATE film_stocks SET cover_image_url = '/film-thumbnails/gold-200.jpg' WHERE name = 'Gold 200';
UPDATE film_stocks SET cover_image_url = '/film-thumbnails/ektar-100.jpg' WHERE name = 'Ektar 100';
